# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React.js CI/CD

on:
  push:
    branches: [production]

jobs:
   version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'AboutBits Tech'
      - run: git config --global user.email 'tech@aboutbits.it'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
